# -*- coding: utf-8 -*-
"""Desafio final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jemVb2xzlzR28Wl1PJ0CIZk6_FACmoB
"""

# Matheus Rodrigues
# João Vitor
# Marcello Henrique
# Rayssa Santos
# Geovanna Pereira
# Christian Yuri



print("「「「「「    Advinhe o numero do Nivus, 10 tentativas  」」」」」")
print(" 「「「「                𝔹𝕆𝔸 𝕊𝕆ℝ𝕋𝔼                   」」」」 ")
print("   「「「                    𖢵                        」」」   ")
print("     「「                                             」」     ")
print("                                                            ")

import random
numero_secreto = random.randint(1,100)
for tentativas in range (1,11):
  numero_digitado = int(input(f" faça eu palpite  {tentativas}:  "))
  if numero_digitado == numero_secreto:
   print("ACERTOUU!!! VOCÊ GANHOU UM NIVUS!! ")
   break
  elif numero_digitado < numero_secreto:
    print("Numero é maior, Acelera essa marcha do Nivus ")
  else:
     print("Numero é menor, Desacelera o Nivus")
while numero_digitado != numero_secreto:
  print("Errou, Você é concorrente?")
  print(f"O numero correto era {numero_secreto} ")
  break